name: Main

on:
  push:
    branches:
      - "*"
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install
        run: npm ci
      - name: Run tests
        run: npm run test
#      - name: Run prettier
#        run: npm run prettier:check
#      - name: Save the coverage artifact
#        uses: actions/upload-artifact@v2
#        with:
#          name: test-code-coverage-report
#          path: ${{github.workspace}}/coverage
